ministryofjustice/operations-engineering-join-github

landing_page_app/main/scripts/github_script.py, landing_page_app/main/scripts/join_github_form.py, landing_page_app/main/services/github_service.py, landing_page_app/main/views.py, landing_page_app/templates/use-slack-rejoin-org.html, tests/scripts/test_github_script.py, tests/views/test_views.py
When user ticks the rejoin button on the form this will check the removed user is in the audit log for each Organisation selected in the form. 
If the username is found it will raise a Slack message to manually invite the user to the Org/s.
If the username is not found, an error message is returned to the user via the form.
=> Check audit log when user rejoins Org

.github/workflows/deploy.yml, .github/workflows/tests.yml, README.md, docs/web-application-security-assessment.md
- Re-assess the current application security posture and it's suitability to be deployed into the PoC environment
- Deploy the application into the PoC environment - to further assess the application functionality, security and value to enable it to be deployed into a production environment
- Increased replica count from `0` to `1` - this will mean 1 pod is created to host the application (enabling it)
- Added an update to the security assessment document to justify the enablement of the PoC environment
- Some minor changes to the deployment pipeline (release on merge to main, updated some names) 
- The application has added several security features since the last review, most notably - a verification process before accessing the production resource of `Github Invitations`. I believe the …
=> 🚀 Deploy to PoC Environment

deployments/templates/deployment.yml
I forgot to commit the important bit of enabling the pods from the [last PR](https://github.com/ministryofjustice/operations-engineering-landing-page-poc/pull/25)
=> 🚀 Deploy into PoC environment (attempt 2)

.github/workflows/deploy.yml
Overview
---
Now the production environment exists it's important to differentiate between DEV and PROD. This PR changes the values in the GitHub deploy action to represent the correct values in secrets.
=> Change secret value prefixes to allow for multi-environment

landing_page_app/templates/pages/external-collaborator.html
Overview
---
This PR connects to https://github.com/ministryofjustice/operations-engineering-join-github/issues/31 and improves the instructions presented to an outside collaborator.
This PR
---
- Revise and expand the instructions for outside collaborators.
- Introduce three distinct paths for user redirection:
1. General instructions for users from non-pre-approved email domains.
2. Specific guidance for accessing the `ministryofjustice` GitHub
organisation.
3. Detailed steps for `moj-analytical-services` GitHub organisation
access.
What it looks like
---
The following page will be presented to the end user:
=> :memo: Improve the Outside Collaborator instructions

join_github_app/main/views.py, join_github_app/templates/pages/digital-justice-user.html, makefile, tests/views/test_views.py
👀 Purpose
---
This PR introduces a new template, digital-justice-user.html, and updates the routing logic to render this template under specific conditions. The new template is designed to provide clear instructions to users with a @digital.justice.gov.uk email domain on how to authenticate via Single Sign-On (SSO).
♻️ What's Changed
---
- New Template: Added digital-justice-user.html. This template includes instructions and relevant information for users with a @digital.justice.gov.uk email domain, guiding them through the process of SSO authentication.
- Conditional Rendering in Route: Modified the join_selection view to conditionally render the digital-justice-user.html template when a user's email address contains the @digital.justice.gov.uk domain. The template is rendered with the …
=> ✨ Add Path Explaining SSO to Digital Justice Users

join_github_app/main/views.py, join_github_app/templates/pages/digital-justice-user.html, join_github_app/templates/pages/join-github.html, join_github_app/templates/pages/select-organisations.html, tests/views/test_views.py
- This pull request introduces several updates to improve how our application handles users with a @digital.justice.gov.uk email domain in the select-organisations feature.
- :technologist: Digital Justice Domain Logic: Implemented logic to identify users with a @digital.justice.gov.uk email domain and pass this information to subsequent processes.
- :fire: Code Clean-up: Removed an unnecessary print statement that was used for debugging.
- :white_check_mark: Testing Digital User Logic: Added unit tests to validate the new logic for handling @digital.justice.gov.uk users in the select-organisations route.
- :fire: Restriction for Digital Users: Removed the ability for users with a @digital.justice.gov.uk email to access the MoJ Analytical Services organisation.
- :children_crossing: UI …
=> ♻️ User Experience Enhancments for Digital Justice Domain in Select Organisations

.mega-linter.yml, tests/views/test_views.py
- To remove false positives of pylint errors
- To enable pylint to check whether a module import is possible
- Add a [precommand](https://megalinter.io/latest/configuration/#pre-commands) to install dependencies in the pylint virtual environment before lining is run
- Megalinter uses a different virtual environment per linter (which is nice isolation 📦 ) - but it does mean that we need to manually install dependencies before the linters run (if they require the dependencies to be installed to run)
- The command used is a bit odd `pip install -r /github/workspace/requirements.txt`- essentially the working directory is the pylint virtual env, and `/github/workspace` is the root of our source code, where we need to go to get the requirements file
=> ✨ Add `PRE_COMMAND` to megalinter to install python dependencies before running linter

join_github_app/config/development.py, join_github_app/config/production.py, join_github_app/config/test.py, join_github_app/main/views.py, join_github_app/templates/pages/digital-justice-user.html, join_github_app/templates/pages/select-organisations.html, makefile
As the title says, we now only display options for the MoJ AS org and the regular MoJ org if we're in the production environment. Otherwise, it'll show the test organisation.
=> Selectable GitHub Organisations for Production and Development Environments

join_github_app/config/development.py
This is to keep the development environment view more aligned with the production environment view.
=> Restored other organisation check boxes

join_github_app/templates/pages/justice-user.html
- This PR aims to clarify the steps involved in the authentication and invitation process, ensuring users understand that Azure AD authentication is a preliminary step before receiving an invitation to join the desired GitHub organisation.
- Revised the justice-user.html template to provide clear and accurate instructions about the Azure AD authentication process and subsequent steps.
- Introduced a more descriptive title - "Authenticate with Azure AD for GitHub Organization Invitation" - to immediately inform users about the process.
- Refined the language used in the template to make it more user-friendly and to accurately convey that Azure AD authentication is for identity verification and does not directly grant access to GitHub organizations.
-
=> :memo: Change wording on the GitHub justice user path

.env.example, deployments/templates/deployment.yml, docker-compose.yaml, operations_engineering_join_github.py
GH_TOKEN is used when authenticating with the gh cli. To remove this clash I've renamed the environment variable we use to populate GitHub admin keys.
=> :recycle: Replace all mentions of GH_TOKEN

.github/workflows/cicd-deploy-to-dev.yml
There is no DEV_KUBE_CLUSTER
This PR fixes the error defined here:
https://github.com/ministryofjustice/operations-engineering-join-github/actions/runs/7558609516/job/20580565981
=> :bug: Fix secret name

.github/workflows/cicd-deploy-to-prod.yml
- This PR connects to https://github.com/orgs/ministryofjustice/projects/52/views/4?pane=issue&itemId=47594256 and relates to the addition of a new continuous integration/delivery pipeline that will build, push and deploy an image after a new git tag has been pushed to main.
- A new file called cicd-deploy-to-prod.yml exists in .github/workflows. This file will trigger on a new tag in the format of `vn.n.n`, which then builds a docker image and pushes it to ECR ready for deployment. It will then upgrade the helm chart in `operations-engineering-join-github-prod` with the new image.
- The image tag name corresponds to the git tag that triggers the pipeline.
=> 🚀  Deploy to Production Pipeline

makefile
If authenticated users want to deploy to dev, they can use the workflow dispatch.
=> :fire: Remove the deploy makefile command

join_github_app/templates/pages/digital-justice-user.html, join_github_app/templates/pages/join-github.html, join_github_app/templates/pages/join-selection.html, join_github_app/templates/pages/justice-user.html, join_github_app/templates/pages/outside-collaborator.html, join_github_app/templates/pages/select-organisations.html
This PR ensures the phase banner appears on every page. Phase banner sits in the `block beforeContent` which in some pages contains the `govukBackLink`. `{{ super() }}` ensures the base `block beforeContent` is included and not overwritten by the subsequent page `block beforeContent`.
=> 🪲 Add `{{ super() }}` to include base content

join_github_app/main/routes/join.py
- Fix the logic so that the correct checkboxes still show after a reminder to select at least one org.
- Moved checkbox creation to above conditional so it is accessible after the error message also.
-
=> 🪲 fix checkboxes vanishing

tests/routes/test_auth.py, tests/services/test_github_service.py
- To fix the tests in `test_github_service.py` (inherited from `test_github_script.py` now refactored) that `assert_not_called` to `get_user` from `add_new_user_to_github_org` which never used `get_user` anyway - this was a copy paste error carried over from the function to rejoin a former user (also now removed).
- Renamed test `TestGithubServiceUserManagementIncorrectInputs` to `TestGithubServiceUserManagementInvalidInputs` for consistency with `TestGithubServiceUserManagementValidInputs`.
- replaced `mock_get_user` with `mock_invite_user_to_org_using_email_address` and updated refs.
- reordered and refactored the tests to match the flow of logic in the if statement in `add_new_user_to_github_org` and to exhaustively test the possible combinations.
- removed refs to …
=> 🐞 Fix tests that test nothing

.gitignore, .pylintrc
- To ensure local development environments have consistent linting rules
- added a `.pylintrc`
- The file and configuration was copied from the operations-engineering repo
=> ✨ Add `.pylintrc`

helm/join-github/templates/deployment.yaml
- Fix syntax error missed in https://github.com/ministryofjustice/operations-engineering-join-github/pull/141
- Removed space
=> 🔧 Fix extra space in `deployment.yaml`

helm/join-github/templates/deployment.yaml
- Fix missing path to helm value in https://github.com/ministryofjustice/operations-engineering-join-github/pull/141
- added `.app.` to the image and repository values in the template
=> 🔧 Fix missing `deployment` in value path

join_github_app/main/services/github_service.py
- To increase visibility in logs whether an invitation has been sent
- Logs per organisaiton
- Logs as INFO instead of DEBUG so logs are visible in production
=> ✨ Add logging whether invites has been sent per org

join_github_app/app_config.py, join_github_app/main/routes/auth.py, join_github_app/main/routes/join.py, join_github_app/templates/components/base.html, join_github_app/templates/pages/errors/internal-error.html, join_github_app/templates/pages/invitation-sent.html, join_github_app/templates/pages/multiple-invitations-sent.html, tests/routes/test_auth.py, tests/views/test_views.py
- To improve the user journey by adding a confirmation page
- 🎛️ Added panel to the invitation sent confirmation page using auth0 authenticated email
- ↩️ Added redirects to ensure the URLs are human readable and match point in user journey
- ✨ Created a page for when multiple invites are sent and logic
- ✏️ Fixed `justce` typo
- ♻️ Updated tests to account for redirects and test new `invitation-sent` logic
-
=> Panel added to  invitation-sent page and redirects to clarify urls

join_github_app/main/routes/auth.py, join_github_app/main/routes/join.py, join_github_app/main/services/github_service.py, tests/routes/test_auth.py, tests/views/test_views.py
- To reduce vulnerability to attack by using the auth0 authenticated email to send GitHub invite
- ♻️ Replaced instances of user input email with `user_input_email` rather than `email` to clarify where it is used
- 🔐 Pass `auth0_email` to `send_github_invitation()` instead of `user_input_email`
- ✏️ Grammar fix; present continuous -> past simple (not sending -> not sent) since the action has finished; it is not ongoing.
- ♻️ Replaced `.get()` dict method with `[]` so that the `unknown key` error raises if empty.
- 🧪 Updated tests to deal with `[]` rather than `.get()` 
-
=> Fix where user input email is used

join_github_app/main/routes/join.py, join_github_app/main/services/github_service.py
- Validates user selection for organisations against valid options set in configuration.
=> validate organisation selection against valid options

app/app.py, app/main/middleware/error_handler.py, app/main/routes/auth.py, app/main/routes/join.py, app/main/services/auth0_service.py, app/templates/pages/errors/400.html, tests/routes/test_auth.py, tests/routes/test_join.py, tests/views/test_views.py
- To centralise business and validation logic into the `join` route, making our security checks around the join process clearer
- To remove business logic from the Authentication process, making the code more transposable for other solutions
- To increase security by adding additional validation checks for user input
- Removed all validation logic from the auth route, clarifying it's the responsibility of only communicating with Auth0 to generate a session token
- Created an Auth0 Service layer, to clarify and separate the responsibility of the route (accepting requestions and storing the session) from the actual communication with Auth0 (or our auth provider)
- Moved all validation checks into the join route, and re-used them in the code where appropriate 
- Added a new …
=> ♻️ Refactor validation logic into `join` route

app/templates/pages/home.html
To include additional (optional) detail on each organisation for the user.
The two <li> components have been changed to <detail> components with bullet pointed details about each organisation. These are optionally expandable:
No notes to speak of.
=> :recycle: Additional Organisation Information

app/templates/pages/justice-and-other-user.html
The page title ("GitHub Organisation Invitation") doesn't explain what this page is for. change to "Verify your work email address.
Replace "To access the Ministry of Justice GitHub organisations you've selected, your email address @justice.gov.uk will be verified using Azure Active Directory (AD).
This secure step is essential to confirm your identity and initiate the process of joining our GitHub organisations
By clicking the button below, you will be redirected to a secure sign-on page where you will be asked to confirm your Office 365 login details
"After successful verification, a GitHub invitation will be sent to your work email address. You will need to accept this invitation to join the selected GitHub organisation
Replace button text "Authenticate" to verify
=> Update wording on GitHub Organisation Invitation

app/templates/pages/home.html
Azure AD creds are not required by everyone, it depends what work email you use and this is explained later. This request on the home page is potentially misleading.
=> Delete line requested get azure ad creds

app/main/routes/join.py, app/templates/pages/already-a-member.html, docker-compose.yaml, tests/routes/test_join.py
- This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/4507 and relates to a 500 internal server error that appears when a user tries to join an organisation they are already a part of.
- Introduced a new error handling method when a user tries to join an organisation they're already part of. Instead of returning an abort statement with a 500 status code, the update now renders a custom page (`already-a-member.html`) informing the user that they are already a member in a more user-friendly way.
- Boolean environment variables in the docker-compose.yaml have been updated from `true/false` to "true"/"false". This change ensures compatibility with systems that require string-type environment variables.
=> 🐛 Handle GitHub Validation Failure if User Exists

.github/workflows/cicd-deploy-to-dev.yml, README.md, app/main/routes/join.py, app/templates/pages/already-a-member.html, helm/join-github/values-dev.yaml, tests/services/test_github_service.py
To handle exceptions more robustly when sending invitations via the GitHub service in the Flask app, ensuring users already part of the organisation receive a proper notification.
- Updated exception handling in the `send_invitation` function to correctly capture and handle `GithubException`.
- Added detailed logging of the exception message for better debugging.
- Improved string matching for error messages to handle slight variations in text.
This change ensures that users who are already part of the organization receive an appropriate message indicating their existing membership rather than encountering an unhandled exception.
The page shown to the user will look as follows:
=> 🐛 Improve GitHub Exception Handling

.github/workflows/trivy-container-scan.yml, makefile, requirements.txt
- This PR responds to the dependabot scan https://github.com/ministryofjustice/operations-engineering-join-github/security/dependabot/5.
- It bumps the Authlib to 1.3.1 and adds options to run a Trivy scan either locally or via a workflow pipeline.
- The pipeline is triggered either manually or weekly at 0600 on a Monday.
- A dependency bump to patch a High CVE.
- An entry in the makefile containing quick options to run a Trivy scan with some relevant arguments.
- A new github-workflow that scans the Dockerfile once a week.
=> ⬆️ Upgrade Authlib Package and Create Trivy Scan Options

requirements.txt
This commit connects to https://github.com/ministryofjustice/operations-engineering/issues/4809
=> :arrow_up: Bump flask-cors version to 5.0.0 to mitigate CVE

requirements.txt
This mitigates https://avd.aquasec.com/nvd/2024/cve-2024-6345/
=> :arrow_up: Bump setuptools to 70.0.0
