landing_page_app/__init__.py, landing_page_app/main/middleware/auth.py, landing_page_app/main/middleware/error_handler.py, landing_page_app/main/routes/auth.py, landing_page_app/main/views.py, landing_page_app/templates/base.html, landing_page_app/templates/home.html, landing_page_app/templates/internal-error.html, landing_page_app/templates/join-github-auth0-user.html, landing_page_app/templates/join-github.html, landing_page_app/templates/thank-you.html, tests/middleware/test_error_handler.py, tests/routes/test_auth.py, tests/views/test_views.py
- To get myself more familiar with the codebase
- Restructure the application into more composable files, easier to find what you need and less chance of changing unrelated code, bringing domain details to a higher level
- Fix some bugs
- Tidy up URLs 
- Restructured the application to now use a `middleware` component, where we can highlight where a request/response is intercepted and processed before it may reach its intended destination
- Restructured the application to use a `routes` component to better highlight the different endpoints the application offers such as `auth` 
- Removed `.html` extensions from endpoints, these just cause an additional maintenance burden
- Removed the `/home` and `/index` endpoints, these just cause an additional maintenance burden
- Fixed Auth0 using …
=> ♻️ Refactor views into composable files 🔧 Fix SSL redirect issue 🔥 Remove `.html` on endpoints

.github/workflows/cicd-deploy-to-dev.yml
This will allow me to interpolate the respository environment variable.
=> :bug: Fix missing id from ecr login

deployments/templates/deployment.yml, deployments/templates/ingress.yml, deployments/templates/service.yml
In anticipation of the replacement with Helm.
=> :recycle: Refactor deployment templates

.github/workflows/cicd-deploy-to-dev.yml, .github/workflows/cicd-deploy-to-prod.yml
This will allow us to utilise the wildcard ssl cert provided by cloud platform.
=> :recycle: Change domain names on prod and dev

join_github_app/templates/pages/home.html
- To make the home page more inline with best practise as exemplified by MoJ Forms 
- Links to the different MoJ GH orgs (moved to this page from join-github page)
- Added what the user will need to complete the process
- Added approximate time to complete the process
- Added the big green super obvious ❇️ beautiful ✳️ Start Now ✅ button 💚
-
=> ♻️ Make home page more like MoJ forms home page 💚

tests/middleware/test_error_handler.py
- To check tests in test_handle_github_exception work as expected and make any improvements.
- Clarify `test_handle_github_exception` purpose with appropriate input.
-
=> Check tests and clarified purpose of test_handle_github_exception

join_github_app/main/config/constants.py, join_github_app/main/routes/auth.py
=> ♻️ Changed logic to use single list of allowed email domains.

join_github_app/__init__.py, join_github_app/main/routes/main.py, requirements.txt
👀 **Purpose**
Setting up transaction and error monitoring on Sentry.
♻️ **What's Changed**
- Sentry has been added into the application.
- An environment variable has been created to hold the DSN key.
- A Sentry Project has been set up to receive information from the application.
- A temporary route has been added to reliably throw an error.
=> Initial Sentry Ingegration

.github/workflows/cicd-deploy-to-dev.yml, .github/workflows/cicd-deploy-to-prod.yml, join_github_app/__init__.py
To enable integration with Sentry for error reporting and performance analytics.
1. The secret containing the DSN Key is now exported during the deployments to both dev and prod.
2. Flask integrations have been included as part of the initialisation of Sentry - this gives us a little more information on flask error peculiarities should we need them.
Here's a link to the [project on Sentry](https://ministryofjustice.sentry.io/projects/operations-engineering-join-github/?project=4506637182173184).
=> Sentry Integration

join_github_app/main/services/github_service.py
=> Test send invite happens using string True

join_github_app/__init__.py, join_github_app/app_config.py
- To centralise application configuration
- Created a central file to contain all application config
- Moved one environment variable into to prove the concept
- More pieces will be centralised in a later PR
=> ✨ Add central configuration file

join_github_app/app_config.py, join_github_app/main/services/github_service.py, tests/test_app_config.py
- To add boolean parser for environment variables to easily use boolean config within the application
- Added boolean parser to the app config file
- Added tests for boolean parser
- Added send email invites into central config
=> ✨ Add boolean parser to config

join_github_app/main/config/github.py
- Missed on previous PR https://github.com/ministryofjustice/operations-engineering-join-github/pull/130
- Removed unused config file
=> 🔥 Remove unused config

operations_engineering_join_github.py
- Fix app not loading
- Removed references to dotenv package
=> 🔧 Fix app attempting to load dotenv

.github/workflows/cicd-deploy-to-dev.yml, .github/workflows/cicd-deploy-to-prod.yml, helm/join-github/templates/deployment.yaml, helm/join-github/values.yaml, join_github_app/__init__.py, join_github_app/app_config.py, join_github_app/config/development.py, join_github_app/config/production.py, join_github_app/main/routes/join.py, tests/views/test_views.py
- To centralise app configuration into one place
- Moved selectable organisations from separate files into one config
- Added environment variables to toggle the selectable orgs
=> ♻️ Refactor `selectable organisations` into centralised config

helm/join-github/templates/deployment.yaml
- To fix typo in https://github.com/ministryofjustice/operations-engineering-join-github/pull/138
=> 🔧 Fix typo

helm/join-github/templates/deployment.yaml
- Fix missing path to helm value in https://github.com/ministryofjustice/operations-engineering-join-github/pull/141
- added `.app.` to the image and repository values in the template
=> 🔧 Fix missing path to helm value

join_github_app/templates/pages/multiple-invitations-sent.html
Update block page title missed earlier
=> update block page title

README.md
- Clarify requirements to deploy the app locally with full functionality
- Updated environment setup instructions to include info about the auth0 client ID and client secret and where to find them.
-
=> update README to clarify how to set up for local deployment

docker-compose.yaml
Set SEND_EMAIL_INVITES to false in local docker compose config
=> SEND_EMAIL_INVITES to false

app/templates/pages/submit-email.html
updated work email address you want to join with
=> updated work email address you want to join with

helm/join-github/templates/ingress.yaml, helm/join-github/values-dev.yaml
- Host name updated to custom domain in ingress
- Secret referencing ssl certificate added
=> Change host name and add certificate secret

app/templates/pages/justice-and-other-user.html
- Few tweaks for consistency
- ♻️ Verify page wording to refer solely to Office 365 (rather than justice.gov.uk)
- ♻️ Use Jinja button component to be consistent with elsewhere in code
- 🔡 Tried to simplify the language a bit
=> Tweak consistency

README.md
Update readme with new urls for dev and prod
=> Update readme with new urls for dev and prod

.github/workflows/mega-linter.yml, .mega-linter.yml
I'm hoping this will speed up the time it takes for Megalinter to complete its scan.
=> :green_heart: Use a lighter weight version of Megalinter
